### ISSUE TITLE
429 Too Many Requests (Support for translation caching?)

### ISSUE THREAD

**Issue by DodoGames7** [WillTDA/Discord.js-Akinator#44]
# disclaimer
I'm not sure if this has something to do with the package but it's lasting longer than usual to fix the behavior mentioned here. Sorry if this turned out to be an issue on my end.

# the problem
when trying to play akinator game with using translation like Arabic, the game works fine until after answering some of akinator questions, the game suddenly stops with an error from the console which is this error. Using english fixes the issue. However, it eventually crashes the bot after answering some of akinator questions again for some strange reason.
![image](https://github.com/WillTDA/Discord.js-Akinator/assets/69091682/72342ebd-f00f-4ab6-a38a-face9327baff)

# Waiting does not work
I have waited for about 3 or 4 hours and more but i still get the same error from the console which just makes me wonder if i did something wrong or not considering that nobody uses my akinator bot a lot and so it's kinda impossible to still give the same error though. This is causing the package's translation to be unusable. What could be possibly causing this? I was honestly afraid to open an new issue thinking that it will just get closed as if it was normal error.

**Comment by WillTDA** [comment]
Hey! 👋 Thanks again for opening an issue.
It seems that this is a problem with the supporting Google Translate package, which (funnily enough) is used to translate Akinator's questions and character names/descriptions into the desired language. There are a couple features in place to make translation efficient and use as few Google Translate requests as possible, however it seems it may not be enough.

Currently there are two viable solutions, those being:
1) Wait it out - Best option is to wait until the package author can find a way to patch this error. If you are playing the Akinator a lot, then that will be why you're getting rate limit so often.
2) Translation Caching - I could potentially add an enhancement to the package, making it so that all successful translation requests are stored in an easily accessible JSON file, which the package can read and write to. This may help to further cut down the number of requests.

We can give it until the end of the week to see if this problem sees any developments. If not, I'll look into implementing caching!

**Comment by DodoGames7** [comment]
Tbh, i usually don't play akinator a lot so i have no clue on why this occurs but yeah that's interesting issue.

**Comment by DodoGames7** [comment]
It's been a month since any updates. Google Translate package still hasn't released a new version so it's still on 9.2.0... I'm not sure anymore about this.

**Comment by DodoGames7** [comment]
Alright! Thanks for information btw.

**Comment by WillTDA** [comment]
Translation caching has been implemented! It will be available from the next update. (v4.1.0)
