### ISSUE TITLE
getting error - Could not find a server matching the region en

### ISSUE THREAD

**Issue by RayZ3R0** [WillTDA/Discord.js-Akinator#49]
Hello, I am getting an error, 
`[error] - Error: Error: Could not find a server matching the region en
    at module.exports (C:\Users\Z3R0\Documents\Discord Botting\Kurumi\node_modules\discord.js-akinator\src\index.js:355:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

I am using discord.js v13 so I can't update to latest version, I am using discord.js-akinator@3.4.5 Can you please help me use this in djs v13

**Comment by WillTDA** [comment]
Hello! 👋 As of the release of Akinator v5, we have deprecated versions relying on Discord.js v13. This is due to recent changes in the Akinator API that rendered the package unusable. Unfortunately, there is nothing that can be done here apart from making the move to Discord.js v14, which I'd highly recommend to keep your bot performing optimally. My apologies.
